services:
  db:
    image: postgres:latest
    container_name: todo_postgres_db
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./backend
    container_name: fastapi_todo_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://todo_user:todo_password@db:5432/tododb
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: